-- Schema v10: who may bring a namespace into existence.
--
-- Until now any unscoped write token could: addressing a namespace by a name
-- that did not exist created it, and writing with no address at all created a
-- "default" one. That is convenient for a single-user install and wrong for a
-- shared one, where an agent's typo silently forks a second store nobody is
-- looking at and where the operator has no way to say "use the space you were
-- given".
--
-- The right is per user rather than per role: an ordinary member may be trusted
-- to organize their own corner without being handed the ability to provision
-- other people. Admin roles (user_manager, superadmin) may always create and do
-- not consult this column.
--
-- 🔴 THIS MIGRATION USED TO END WITH A BACKFILL, AND THE BACKFILL WAS A BUG:
--
--     UPDATE app_user SET can_create_namespace = true
--      WHERE can_create_namespace = false;
--
-- The intent was one-time and reasonable — accounts that predate the column had
-- the right since the deployment was created, and taking it away mid-upgrade
-- would break their running writes with a permission error. But migrations are
-- re-applied on EVERY start, and that statement cannot tell "predates the
-- column" from "was created yesterday without the right". So every restart
-- re-granted namespace creation to every account: a user provisioned with the
-- right withheld got it back, an admin's revocation was silently undone, and
-- `create_user`'s `can_create_namespace=False` default meant nothing.
--
-- Removed rather than guarded, because it has no remaining work to do. A
-- database older than this migration was backfilled the first time it ran; one
-- created after it has an empty `app_user` when it runs, so the statement was
-- always a no-op there. Deleting it is correct for both.
--
-- If your deployment ran a version between v10 and this fix, assume the right
-- is set on every account and re-check the ones that should not have it.
ALTER TABLE app_user
    ADD COLUMN IF NOT EXISTS can_create_namespace boolean NOT NULL DEFAULT false;
